In [29]:
import pandas as pd
import re

In [30]:
df = pd.read_csv('../data/used_cars.csv')
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [31]:
df['age_of_car'] = df['model_year'].max() - df['model_year']
df['milage_of_car'] = df.apply(lambda x: re.sub('[,mi.]', '', x['milage']), axis=1).astype(int)
df['price_of_car'] = df.apply(lambda x: re.sub(r'[$,]', '', x['price']), axis=1).astype(int)
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,age_of_car,milage_of_car,price_of_car
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",11,51000,10300
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",3,34742,38005
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598",2,22372,54598
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",9,88900,15500
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999",3,9835,34999

In [32]:
mean_price_of_car = df['price_of_car'].mean()
std_price_of_car = df['price_of_car'].std()
df['normalized_price'] = df.apply(lambda x: (x['price_of_car'] - mean_price_of_car)/std_price_of_car, axis=1)
df['normalized_price']

0      -0.435179
1      -0.083193
2       0.127617
3      -0.369114
4      -0.121384
          ...
4004    3.879994
4005    0.118749
4006    0.590070
4007    0.234350
4008   -0.057847
Name: normalized_price, Length: 4009, dtype: float64

In [35]:
mean_age_of_car = df['age_of_car'].mean()
std_age_of_car = df['age_of_car'].std()
df['normalized_age'] = df.apply(lambda x: (x['age_of_car'] - mean_age_of_car)/std_age_of_car, axis=1)
df['normalized_age']

0       0.412066
1      -0.898374
2      -1.062179
3       0.084456
4      -0.898374
          ...
4004   -1.225984
4005   -1.062179
4006   -1.062179
4007   -0.734569
4008   -0.734569
Name: normalized_age, Length: 4009, dtype: float64

In [37]:
mean_milage_of_car = df['milage_of_car'].mean()
std_milage_of_car = df['milage_of_car'].std()
df['normalized_milage'] = df.apply(lambda x: (x['milage_of_car'] - mean_milage_of_car)/std_milage_of_car, axis=1)
df['normalized_milage']

0      -0.262303
1      -0.573184
2      -0.809719
3       0.462410
4      -1.049448
          ...
4004   -1.223857
4005   -1.029083
4006   -1.197048
4007   -0.606494
4008   -0.415277
Name: normalized_milage, Length: 4009, dtype: float64

In [38]:
df2 = df[['normalized_age', 'normalized_milage', 'normalized_price']]
df2.head()

   normalized_age  normalized_milage  normalized_price
0        0.412066          -0.262303         -0.435179
1       -0.898374          -0.573184         -0.083193
2       -1.062179          -0.809719          0.127617
3        0.084456           0.462410         -0.369114
4       -0.898374          -1.049448         -0.121384